package soho.demo.domain;

import com.soho.mybatis.crud.domain.IDEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table rbac_role
 *
 * @mbg.generated do_not_delete_during_merge
 */
@SuppressWarnings("serial")
public class RbacRole implements IDEntity<Long> {
    private Long id;

    /**
     * Database Column Remarks:
     *   角色编码
     */
    private String code;

    /**
     * Database Column Remarks:
     *   角色名称
     */
    private String name;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    private Long ctime;

    /**
     * Database Column Remarks:
     *   更新时间
     */
    private Long utime;

    /**
     * Database Column Remarks:
     *   状态
     */
    private Integer state;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public Long getCtime() {
        return ctime;
    }

    public void setCtime(Long ctime) {
        this.ctime = ctime;
    }

    public Long getUtime() {
        return utime;
    }

    public void setUtime(Long utime) {
        this.utime = utime;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }
}