package soho.demo.domain;

import com.soho.mybatis.crud.domain.IDEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table rbac_user
 *
 * @mbg.generated do_not_delete_during_merge
 */
@SuppressWarnings("serial")
public class RbacUser implements IDEntity<Long> {
    private Long id;

    /**
     * Database Column Remarks:
     *   登陆账号
     */
    private String username;

    /**
     * Database Column Remarks:
     *   登录密码
     */
    private String password;

    /**
     * Database Column Remarks:
     *   用户UID
     */
    private String uid;

    /**
     * Database Column Remarks:
     *   1.普通用户 2.后台用户
     */
    private Integer utype;

    /**
     * Database Column Remarks:
     *   区号
     */
    private String areacode;

    /**
     * Database Column Remarks:
     *   手机号码
     */
    private String mobile;

    /**
     * Database Column Remarks:
     *   性别 1.男 2.女
     */
    private Integer sex;

    /**
     * Database Column Remarks:
     *   年龄
     */
    private Integer age;

    /**
     * Database Column Remarks:
     *   头像
     */
    private String headimg;

    /**
     * Database Column Remarks:
     *   昵称
     */
    private String nickname;

    /**
     * Database Column Remarks:
     *   真实姓名
     */
    private String realname;

    /**
     * Database Column Remarks:
     *   身份证
     */
    private String idno;

    /**
     * Database Column Remarks:
     *   邮箱
     */
    private String email;

    /**
     * Database Column Remarks:
     *   微信账号
     */
    private String wxcat;

    /**
     * Database Column Remarks:
     *   支付宝账号
     */
    private String alipay;

    /**
     * Database Column Remarks:
     *   二级密码
     */
    private String password2;

    /**
     * Database Column Remarks:
     *   用户星级
     */
    private Integer level;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    private Long ctime;

    /**
     * Database Column Remarks:
     *   更新时间
     */
    private Long utime;

    /**
     * Database Column Remarks:
     *   1.正常 2.禁用 3.冻结
     */
    private Integer state;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    public Integer getUtype() {
        return utype;
    }

    public void setUtype(Integer utype) {
        this.utype = utype;
    }

    public String getAreacode() {
        return areacode;
    }

    public void setAreacode(String areacode) {
        this.areacode = areacode == null ? null : areacode.trim();
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    public Integer getSex() {
        return sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public String getHeadimg() {
        return headimg;
    }

    public void setHeadimg(String headimg) {
        this.headimg = headimg == null ? null : headimg.trim();
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    public String getRealname() {
        return realname;
    }

    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    public String getIdno() {
        return idno;
    }

    public void setIdno(String idno) {
        this.idno = idno == null ? null : idno.trim();
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    public String getWxcat() {
        return wxcat;
    }

    public void setWxcat(String wxcat) {
        this.wxcat = wxcat == null ? null : wxcat.trim();
    }

    public String getAlipay() {
        return alipay;
    }

    public void setAlipay(String alipay) {
        this.alipay = alipay == null ? null : alipay.trim();
    }

    public String getPassword2() {
        return password2;
    }

    public void setPassword2(String password2) {
        this.password2 = password2 == null ? null : password2.trim();
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public Long getCtime() {
        return ctime;
    }

    public void setCtime(Long ctime) {
        this.ctime = ctime;
    }

    public Long getUtime() {
        return utime;
    }

    public void setUtime(Long utime) {
        this.utime = utime;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }
}