package soho.demo.domain;

import com.soho.mybatis.crud.domain.IDEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table rbac_user_role
 *
 * @mbg.generated do_not_delete_during_merge
 */
@SuppressWarnings("serial")
public class RbacUserRole implements IDEntity<Long> {
    private Long id;

    /**
     * Database Column Remarks:
     *   用户ID
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   角色ID
     */
    private Long roleId;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    private Long ctime;

    /**
     * Database Column Remarks:
     *   更新时间
     */
    private Long utime;

    /**
     * Database Column Remarks:
     *   状态
     */
    private Integer state;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getRoleId() {
        return roleId;
    }

    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    public Long getCtime() {
        return ctime;
    }

    public void setCtime(Long ctime) {
        this.ctime = ctime;
    }

    public Long getUtime() {
        return utime;
    }

    public void setUtime(Long utime) {
        this.utime = utime;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }
}